name: despliegue_remoto self-hosted runner
on:
  push:
    branches:
      - main # O la rama que desees

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Copiar código
        uses: actions/checkout@v3

      - name: Añadir clave SSH al agente
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY_172}} # Usa el nombre del secreto que creaste

      - name: Conectar y ejecutar comandos en el servidor
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST_172}} # Tu nombre de host
          username: ${{secrets.SSH_USERNAME_172}} # Tu nombre de usuario
          key: ${{secrets.SSH_PRIVATE_KEY_172}} # Clave privada
          script: |
                  # Checkout del repositorio
                  - name: Checkout repository
                  uses: actions/checkout@v3
                  # Build de la imagen Docker usando ruta relativa
                  
                  - name: Build Docker image
                  run: |
                  cd nginx-hello-worldb
                  docker build -t nginx-hello-world .
                  # Detener y eliminar contenedor anterior (si existe)
                  
                  - name: Stop previous container if exists
                    run: |
                    if (docker ps -a -q -f name=nginx-hello-world) 
                     {
                     docker stop nginx-hello-world-deployment
                     docker nginx-hello-world-deployment
                     } else {
                     Write-Host "No container to stop/remove"
                     }
	                # Ejecutar contenedor con volumen y puerto
                  -name: Run Docker container
                  run: |
                  docker run -d -p 8086:8085 `
	                  -v dataprotection-keys:/root/.aspnet/DataProtection-Keys `
                    --name nginx-hello-world-deployment nginx-hello-world
          
