name: prueba self-hosted runner
 
# Este workflow se ejecuta manualmente desde GitHub

on:

  workflow_dispatch:
 
jobs:

  test:

    # Se asegura de que se ejecute en tu runner Windows con etiqueta 'prod'

    runs-on: [self-hosted, linux]
 
    steps:

      - name: Checkout repository

        uses: actions/checkout@v4
 
      - name: Say Hello
        run: echo "Hola desde el servidor Windows"
      - name: nombre Servidor
        run: echo $HOSTNAME
      - name: hacer conexion
        run: ssh root@10.34.7.172
        
